eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
---
spring:
  profiles: subject
  application:
    name: subject
words: I,You,He,She,Martin,Ahmed,Jon,Joel

---
spring:
  profiles: verb
  application:
    name: verb
words: noticed,found,knew,had,saw,bought

---
spring:
  profiles: article
  application:
    name: article
words: a,the,one

---
spring:
  profiles: adjective
  application:
    name: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
  application:
    name: noun
words: skunk,child,person,suspect,backpack,sandwich,groundhog  
